"""
Flood Watch Assam - River Level Scraper v4 (Sivasagar & Charaideo)
Source: SmartAxom (smartaxom.nesdr.gov.in), built by NESAC (North
Eastern Space Applications Centre) for ASDMA, aggregating live CWC
station data. Discovered via browser DevTools network inspection of
https://smartaxom.nesdr.gov.in/analytics/flood/waterlevelinfo

This is a COMPLETELY DIFFERENT domain/infrastructure than the CWC
backend API that was blocked from cloud IPs (ffs.india-water.gov.in).
NESAC (a space research agency) likely doesn't apply the same
datacenter-IP firewall rules CWC's own infrastructure does.

IMPORTANT CAVEAT: the request body is a single opaque "key" field
containing what looks like an encrypted/encoded blob, generated by
their frontend JavaScript. This scraper currently reuses a captured
key value verbatim. Two possible outcomes when this is actually run:
  1. The key is static (baked into the JS bundle, doesn't rotate) ->
     this works indefinitely, no changes needed.
  2. The key is session/timestamp-bound and rotates -> this will stop
     working after some time, and someone will need to re-capture a
     fresh key from DevTools periodically (or the encryption scheme
     needs to be reverse-engineered from their JS bundle for a
     permanent fix).
Test results will tell us which scenario we're in.

The API appears to return ALL Assam CWC stations in one call (71 seen
in testing), not filtered by district - so this scraper fetches once
and filters client-side.
"""

import json
import sys
from datetime import datetime, timezone

import requests

API_URL = "https://smartaxom.nesdr.gov.in/api_v2/dataCWC"

# Captured from a real browser session via DevTools - see caveat above
# about whether this remains valid over time.
CAPTURED_KEY = "wEcrwgNfG2BKs7bz2t/mXe/4eXqmP3heAWZWr+QKrVXLWl499BAB9GWCUIOhBO40"

HEADERS = {
    "Accept": "*/*",
    "Origin": "https://smartaxom.nesdr.gov.in",
    "Referer": "https://smartaxom.nesdr.gov.in/analytics/flood/waterlevelinfo",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                  "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
}

# Station codes confirmed present in this API's response (from browser
# search results): 017-UBDDIB, 016-UBDDIB, 018-ubddib. Matched here by
# name and district, since those are cleaner and more stable than codes.
TARGET_NAMES = ["sivasagar", "sibsagar", "bihubar", "nanglamoraghat", "desangpani"]
TARGET_DISTRICTS = {"SIVASAGAR", "CHARAIDEO"}


def fetch_all_stations() -> list:
    """
    Replays the captured multipart/form-data POST request. Returns the
    raw list of station records from the API's "data" field.
    """
    files = {"key": (None, CAPTURED_KEY)}
    resp = requests.post(API_URL, headers=HEADERS, files=files, timeout=20)
    resp.raise_for_status()
    payload = resp.json()

    if not payload.get("success"):
        raise RuntimeError(f"API returned success=false: {payload}")

    return payload.get("data", [])


def filter_target_stations(all_stations: list) -> dict:
    matches = {}
    for station in all_stations:
        name = (station.get("name") or "").strip()
        district = (station.get("district_n") or "").strip().upper()
        name_lower = name.lower()

        is_target = any(t in name_lower for t in TARGET_NAMES) or district in TARGET_DISTRICTS
        if not is_target:
            continue

        matches[station.get("stationcode", name)] = {
            "name": name,
            "district": station.get("district_n"),
            "river": station.get("river_name"),
            "basin": station.get("basin_name"),
            "current_level_m": station.get("current_flow_level"),
            "warning_level_m": station.get("warning_flow_level"),
            "danger_level_m": station.get("danger_flow_level"),
            "high_flow_level_m": station.get("high_flow_level"),
            "status_color": station.get("color"),
            "last_update": station.get("last_update"),
            "lat": station.get("lat"),
            "lon": station.get("lon"),
            "stationcode": station.get("stationcode"),
        }
    return matches


if __name__ == "__main__":
    try:
        all_stations = fetch_all_stations()
        matches = filter_target_stations(all_stations)
        result = {
            "generated_at_utc": datetime.now(timezone.utc).isoformat(),
            "source": API_URL,
            "total_stations_returned": len(all_stations),
            "matched_stations": matches,
        }
    except Exception as exc:
        result = {
            "generated_at_utc": datetime.now(timezone.utc).isoformat(),
            "source": API_URL,
            "error": str(exc),
            "matched_stations": {},
        }

    print(json.dumps(result, indent=2, default=str))
